query GetLookbook($slug: ID!) {
	lookbook(id: $slug, idType: SLUG) {
		id
		title
		slug
		content
		gallery {
			media {
				video {
					...ImageBase
					mediaItemUrl
				}
				images {
					...ImageBase
				}
			}
		}
	}
}
